### ISSUE TITLE
raster, sp, and rgdal will be deprecated soon

### ISSUE THREAD

**Issue by hannahlowens** [hannahlowens/voluModel#5]
Conversion to terra, sf, etc will be necessary to keep the package from being archived.

**Comment by rsbivand** [comment]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
[00check.log](https://github.com/hannahlowens/voluModel/files/11141570/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html).

**Comment by hannahlowens** [comment]
Version 0.2.0 no longer depends on these packages.

**Comment by rsbivand** [comment]
Thanks, running CMD check on 0.2.0 in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path gives this log:
[00check.log](https://github.com/hannahlowens/voluModel/files/11364988/00check.log)
